# Generated by Django 5.2.3 on 2025-07-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
